firebase/superstatic

lib/index.js, package.json
Right now the path for "main" isn't consistent with the documented exports of the library. Also, there's no need to do `var exports` because `exports` is already defined in the context of a module.
=> Set "main" to correct path and fix index file

lib/middleware/static-router.js, test/unit/middleware/static-router.js
This was bothering me :grimacing: -- for example, if I want `js` don't send `html`. 
Content type warnings can be hard to keep track of in the console when working with media iframes, and with fonts or async metrics scripts, you might not find out until you push.
=> make sure path and extensions match

lib/dfs.js, test/unit/dfs.js
This uses the etag package's implementation of isStats. The problem is caused by older versions of the ubiquitous graceful-fs package, which causes the return value of fs.stat to fail an instanceof check for fs.Stats. See #177 for more information.
=> Detect "fake" stats-like objects that aren't instances of fs.Stats

lib/cli/index.js
There was a bug in how `.env.json` was used by the CLI that caused the env file not to be loaded. Now a `.env.json` is **only used by the CLI** and if you're using a middleware you have to manually pass env config. I think this is the behavior we want going forward.
=> [4.0] Fix how CLI picks up .env.json

lib/middleware/rewrites.js, test/unit/middleware/rewrites.spec.js
Previously, Superstatic disallowed a mismatch of URL to rewritten static asset. This prevents a valid use case of a URL that is an HTML representation of a non-HTML file, e.g. GitHub file browsing.
This PR removes the extension check and always serves the matched file. In addition, added a test to ensure that the mime type is taken from the static asset, not the file extension.
=> Allow mismatched extensions when globbing rewrites.

README.md
I believe it's now `public` as of superstatic 3.0.0.
=> Readme: change 'root' to 'public'

lib/providers/fs.js, test/integration/serving-files.spec.js
This change makes it so that the fs provider cannot serve files above the specified root. Previously, a string of `../../../` would let you access files outside the specified public directory.
=> Don't allow fs provider to reach above root dir.

.eslintrc, .travis.yml, lib/middleware/clean-urls.js, lib/middleware/env.js, lib/middleware/files.js, lib/middleware/headers.js, lib/middleware/redirects.js, lib/middleware/rewrites.js, lib/providers/fs.js, package.json
Updating some dependencies, but it still doesn't get rid of all the warnings. Have to wait for a new patch of mocha ([commit](https://github.com/mochajs/mocha/commit/c9bcfc1b015c8d15d5fe5159e30818cd02f6a098)) for the install errors to go away completely
=> Updating dependencies

lib/loaders/config-file.js
The `superstatic` CLI tool expects `firebase.json` to be in a format that's incompatible with the format expected by `firebase` itself. This PR applies the same "tweak" to the config file handling [that `serve.js` does](https://github.com/firebase/firebase-tools/blob/master/commands/serve.js#L23) so that the two are compatible.
=> Make compatible with (new) firebase.json

lib/middleware/rewrites.js, lib/responder.js, lib/superstatic.js, test/unit/responder.spec.js
Adds the ability to define custom rewriters that handle keys other than `destination` in configuration. A rewriter should return a Promise that resolves to something that `Responder.prototype.handle` can...handle.
=> Add extensible rewriters

lib/middleware/redirects.js, package.json, test/unit/middleware/redirects.spec.js
This updates redirects to properly match and redirect when a query string is present, preserving the query string. It explicitly **does not**:
1. Allow matching based on query strings
2. Allow captures to be inserted into query strings
=> Redirects preserve query parameters.

lib/providers/fs.js, test/unit/providers/fs.spec.js, test/unit/providers/memory.spec.js
=> Disallow upward tree traversal in Windows.

changelog.txt, lib/middleware/files.js
An empty Location header is an error in most cases, when redirecting to "no path" it should always be a "/".
=> Shouldn't redirect to an empty string

bin/server, package.json
`update-notifier` depended on an older version of things that included an old version of `got`, so this is to clean up those dependencies.
`nsp` and `supertest` were flagged by `npm audit`, so I upgraded those as well.
=> updating update-notifier, a few deps

.travis.yml, package.json
Update for `.travis.yml`, mostly.
Remove some extra stuff that was unnecessary and removed `nsp`. `nsp` is replaced by `npm audit`, which only exists in `npm` >= `6`, so I added that as a check for when `npm` supports it.
=> Travis Update, Removing nsp

changelog.txt, lib/providers/fs.js
When serving content locally from a drive other than "C:\\" on Windows we would get `EINVAL` back as the error instead of the more expected `EISDIR` when the same thing is done on the "C:\\" drive.
=> Fixing `EINVAL` error when serving "/" on Windows

package.json
this is a breaking change to bring us up to current times.
=> BREAKING: bring superstatic up to requiring node >=8.6.0

lib/responder.js, test/unit/responder.spec.js
Turns out that handleStack expected `true` to be returned if we have responded to a request. In the 304 case, we were always returning `undefined` which meant the stack attempted to look for a 404 page.
This should address https://github.com/firebase/firebase-tools/issues/2610
=> return true (indicating we responded) on a 304 error

README.md, lib/middleware/files.js, test/unit/middleware/files.spec.js
This adds i18n rewrite support for superstatic.
This can serve different content based on the `accept-language` or `x-country-code` headers. It also includes a way to override the language or country based on cookie values.
=> add i18n support

examples/middleware/index.js, examples/server/index.js, package.json, src/config.ts, src/index.ts, src/options.ts, src/responder.js, src/server.js, src/superstatic.js, src/utils/patterns.js, test/integration/clean-urls.spec.ts, test/integration/error-pages.spec.js, test/integration/serving-files.spec.js, tsconfig.json
Woo! Now when superstatic is used in `firebase-tools`, I have actual types to check against. Very useful.
=> better types and export types for superstatic

package-lock.json, package.json, src/bin/server.ts
Since `update-notifier@6` is an es module, we need to swap to `update-notifier-cjs` which will be maintained as a commonjs module. Thanks, community!
=> swap update-notifier for update-notifier-cjs

changelog.txt, src/utils/pathutils.ts, test/unit/providers/fs.spec.ts
This fixes an issue where Windows users were getting Not Found issues.
I started working on fixing the tests in windows, but it's more tedious than I thought.
=> manually join paths instead of using the os sep

src/providers/fs.ts, test/unit/providers/fs.spec.ts
fixes: https://github.com/firebase/superstatic/issues/388
=> fs provider should return null if path has null bytes

.github/workflows/node-test.yml, changelog.txt, package-lock.json, package.json, src/middleware/redirects.js, src/providers/fs.ts
* Updates dependencies to address `npm audit` issues.
* Fixes issue where redirects of unicode paths may not have been handled correctly.
* Fixes issue in Node 22 where `mtime` from `stat`-ing a file is no longer available.
=> audit fix, and node 22 fix

changelog.txt, package-lock.json, package.json, src/middleware/files.js, src/middleware/headers.js, src/middleware/rewrites.ts
`fast-url-parser` was a faster drop in replacement for Node's builtin url parser. However, it hasn't been updated in 10 years, and uses `punycode` which is deprecated as of node 22. During those 10 years, node's built in parser has gotten much more efficient and so this is no longer necessary.
=> fast-url-parser -> url

.github/workflows/node-test.yml, changelog.txt, eslint.config.mjs, package-lock.json, package.json
- drops node 18
- upgrades eslint
- upgrades typescript
=> various dependency updates
